'use strict';
const $=id=>document.getElementById(id);
const canvas=$('canvas'), gl=canvas.getContext('webgl',{alpha:false,antialias:true,preserveDrawingBuffer:true});
const state={float:45,speed:40,rotation:35,size:100,visible:true,paused:matchMedia('(prefers-reduced-motion: reduce)').matches};
let spheres=[],time=0,last=0;
function pauseUI(){$('pause').innerHTML=state.paused?'▶ <span>재생</span>':'Ⅱ <span>일시정지</span>';$('pause').setAttribute('aria-pressed',String(state.paused));$('status').textContent=state.paused?'움직임을 멈춘 상태':'자유롭게 떠다니는 중';}
$('pause').onclick=()=>{state.paused=!state.paused;pauseUI();};pauseUI();
for(const name of ['float','speed','rotation','size']) {const el=$(name);el.oninput=()=>{state[name]=Number(el.value);$(name+'-out').value=el.value;el.style.setProperty('--fill',((el.value-el.min)/(el.max-el.min)*100)+'%');};el.oninput();}
$('visible').onchange=()=>state.visible=$('visible').checked;
if(!gl){$('error').hidden=false;}else{start();}
function start(){
const vert=`attribute vec3 position;attribute vec2 uv;uniform vec3 center;uniform vec3 angles;uniform vec2 viewport;uniform float radius;varying vec2 texUV;varying float facing;
void main(){vec3 p=position;float c=cos(angles.x),s=sin(angles.x);p=vec3(p.x,c*p.y-s*p.z,s*p.y+c*p.z);c=cos(angles.y);s=sin(angles.y);p=vec3(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);c=cos(angles.z);s=sin(angles.z);p=vec3(c*p.x-s*p.y,s*p.x+c*p.y,p.z);facing=p.z;vec3 world=p*radius+center;float w=1.0-world.z/1800.0;gl_Position=vec4(world.x/(viewport.x*.5),world.y/(viewport.y*.5),-world.z/1800.0,w);texUV=uv;}`;
const frag=`precision mediump float;uniform sampler2D lettering;uniform vec3 color;uniform float visible;varying vec2 texUV;varying float facing;void main(){if(facing<0.0)discard;vec4 ink=texture2D(lettering,texUV);if(visible<.5 && ink.a<.02)discard;vec3 base=visible>.5?color:vec3(1.0);gl_FragColor=vec4(mix(base,vec3(.13,.11,.10),ink.a),1.0);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
let program;try{program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vert));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('3D initialization failed');}catch(e){$('error').hidden=false;return;}
gl.useProgram(program);const uniforms={};for(const n of ['center','angles','viewport','radius','lettering','color','visible'])uniforms[n]=gl.getUniformLocation(program,n);
const points=[],uvs=[],indices=[],nx=96,ny=48;
for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++){const u=i/nx,v=j/ny,lon=(u-.5)*Math.PI*2,lat=(.5-v)*Math.PI;points.push(Math.sin(lon)*Math.cos(lat),Math.sin(lat),Math.cos(lon)*Math.cos(lat));uvs.push(u,v);}
for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const a=j*(nx+1)+i;indices.push(a,a+nx+1,a+1,a+1,a+nx+1,a+nx+2);}
function attribute(name,values,size){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0);}
attribute('position',points,3);attribute('uv',uvs,2);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(indices),gl.STATIC_DRAW);gl.enable(gl.DEPTH_TEST);gl.clearColor(1,1,1,1);
function texture(char){const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#211c19';ctx.font='500 215px "Apple SD Gothic Neo", "Noto Sans KR", sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(char,512,265,290);const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t;}
const segmenter=typeof Intl.Segmenter==='function'?new Intl.Segmenter('ko',{granularity:'grapheme'}):null;
function rebuild(){for(const s of spheres)gl.deleteTexture(s.texture);spheres=[];const chars=segmenter?Array.from(segmenter.segment($('text').value),x=>x.segment):Array.from($('text').value);let row=0,col=0;for(const ch of chars){if(ch==='\n'){row++;col=0;continue;}if(/\s/u.test(ch)){col+=.4;continue;}spheres.push({texture:texture(ch),col,row,index:spheres.length});col++;}$('count').textContent=spheres.length+'개의 구';$('empty').hidden=spheres.length>0;}
$('text').addEventListener('input',e=>{if(!e.isComposing)rebuild();});$('text').addEventListener('compositionend',rebuild);rebuild();document.fonts.ready.then(rebuild);
function render(now){const dt=Math.min((now-last)/1000,.04);last=now;if(!state.paused)time+=dt*state.speed/40;const width=canvas.clientWidth,height=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);gl.viewport(0,0,canvas.width,canvas.height);}gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform2f(uniforms.viewport,width,height);gl.uniform1f(uniforms.visible,state.visible?1:0);
// Wrap long text and scale the composition to leave room for floating motion.
const columns=Math.max(2,Math.floor((width-50)/104)),layout=[],rows=new Map();let offset=0,prevRow=-1;
for(const s of spheres){if(s.row!==prevRow){if(prevRow>=0)offset=Math.max(...layout.map(x=>x.row))+1;prevRow=s.row;}const row=offset+Math.floor(s.col/columns),col=s.col%columns;layout.push({...s,row,col});rows.set(row,Math.max(rows.get(row)||0,col+1));}
const rowCount=layout.length?Math.max(...layout.map(x=>x.row))+1:1;const unit=Math.min(112,(width-66)/Math.max(1,...rows.values()),(height-110)/Math.max(rowCount,1));const r=unit*.46*state.size/100;const amp=state.float/100*unit*.55;const rot=state.rotation/100;
for(const s of layout){const i=s.index,phase=i*2.399;const x=(s.col-(rows.get(s.row)-1)/2)*unit+Math.sin(time*.63+phase)*amp*.45,y=((rowCount-1)/2-s.row)*unit*1.15+Math.sin(time*.82+phase)*amp,z=Math.sin(time*.49+phase)*amp*.8;gl.uniform3f(uniforms.center,x,y,z);gl.uniform1f(uniforms.radius,r);gl.uniform3f(uniforms.angles,Math.sin(time*.47+phase)*rot*.9,Math.sin(time*.57+phase*.6)*rot*1.9,Math.sin(time*.39+phase)*rot*.9);gl.uniform3f(uniforms.color,...(i%7===0?[.68,.91,.92]:[.85,1,.59]));gl.bindTexture(gl.TEXTURE_2D,s.texture);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);}
requestAnimationFrame(render);}
requestAnimationFrame(render);
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'configure_moving_identity',description:'캔버스의 텍스트와 구 움직임을 조정합니다.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:240},float:{type:'number',minimum:0,maximum:100},speed:{type:'number',minimum:0,maximum:100},rotation:{type:'number',minimum:0,maximum:100},size:{type:'number',minimum:40,maximum:160},visible:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object')throw Error('설정이 필요합니다.');for(const [k,v]of Object.entries(input)){if(!['text','float','speed','rotation','size','visible'].includes(k))throw Error('알 수 없는 설정');if(k==='text'&&(typeof v!=='string'||v.length>240))throw Error('텍스트 길이를 확인하세요.');if(k==='visible'&&typeof v!=='boolean')throw Error('표시 여부를 확인하세요.');if(!['text','visible'].includes(k)&&(typeof v!=='number'||!Number.isFinite(v)||v<(k==='size'?40:0)||v>(k==='size'?160:100)))throw Error('조절 범위를 확인하세요.');}for(const [k,v]of Object.entries(input)){if(k==='text'){$('text').value=v;rebuild();}else if(k==='visible'){state.visible=v;$('visible').checked=v;}else{$(k).value=v;$(k).oninput();}}return {text:$('text').value,count:spheres.length,...state};}})).catch(()=>{});}catch(e){}}
}
